channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3
  - notebook<5.7.5
  - bokeh=1.1.0
  - dask=1.2.0
  - dask-image=0.2.0
  - nodejs=8.9
  - notebook<5.7.5
  - nc-time-axis
  - tornado=5
  - cartopy
  - numpy
  - pandas
  - pyarrow==0.10.0
  - python-graphviz
  - seaborn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - py-xgboost
  - holoviews 
  - geoviews
  - pip:
    - dask_xgboost
    - mimesis
    - jupyterlab
    - dask-labextension
    - wget
