name: geo-stack
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - xarray
  - matplotlib
  - dask
  - distributed
  - intake
  - intake-xarray
  - bokeh=1.4.0
  - dask-labextension=3.0.0
  - holoviews>=1.12.3
  - panel
  - geoviews
  - hvplot
  - rasterio
  - geoviews
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab
  - ipywidgets
  - ipyleaflet
  - tornado=5
  - python-wget
  - pip
  - nc-time-axis
  - numpy
  - pandas
  - python-wget
  - pip:
    - graphviz
  
