name: geo-stack
channels:
  - conda-forge
dependencies:
  - python=3.6
  - scipy
  - xarray
  - matplotlib
  - dask
  - distributed
  - intake
  - intake-xarray
  - bokeh
  - holoviews>=1.12.3
  - panel
  - geoviews
  - hvplot
  - rasterio
  - geoviews
  - datashader
  - netcdf4
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - nbserverproxy
  - jupyter
  - jupyterlab=1.0.0
  - ipywidgets
  - ipyleaflet
  - tornado=5.1.1
  - python-wget
  - pip
  - nc-time-axis
  - numpy
  - pandas
  - python-wget
  - pip:
    - graphviz
    - dask_labextension
